---
title: "Calculating Heterozygosity and Inbreeding Statistics"
output: 
  github_document: default
  html_notebook: default
---

\
Today we will explore how to calculate heterozygosity and other measures of genetic diversity. We will start by doing some calculations by hand, and then move to the computer cluster to see how we can use different programs to compute the calculations for us. If this material is review for you, please bear with us. We're starting simple so that everyone is on the same page.
\
Remember there are two kinds of heterozygosity:

* __Observed heterozygosity ($H_{o}$)__ is the proportion of individuals that are heterozygous (have two different alleles) at a given locus
* __Expected heterozygosity ($H_{e}$)__ is the probability of picking two different alleles from a population if you sampled randomly

$H_{e}$ = $H_{o}$ if a population meets Hardy-Weinberg Proportions (HWP).
\
\
In this lab, we are going to calculate the allele frquencies, $H_{o}$ and $H_{e}$ at a particular locus in a sample population. As a quick reminder, the equation for these terms are as follows:
\
\
___Allele frequencies___ can be calculated as: $\frac{copies\,of\,given\,allele}{total\,number\,alleles\,in\,population}$
\
\
___Observed heterozygosity ($H_{o}$)___ can be calculated as: $\frac{N(Het)}{N}$ where $N(Het)$ is the number of individuals that are heterozygous at a given locus and $N$ is the total number of individuals in the population.
\
\
___Expected heterozygosity ($H_{e}$)___ can be calculated as: $2pq$ where $p$ is the allele frequency of allele 1 and $q$ is the allele frequency of allele 2 (at a biallelic locus).

## *__Heterozygosity by hand__*
\
Navigate to <https://github.com/rclark848/PIRE_Bioinformatics>. This is a repository that contains .md (markdown) and .Rmd (R markdown) copies of all the labs we will be doing over the next three days. It is also home to any data, scripts, or input files you will need for the upcoming analyses. Open up the directory titled `Day_1_Labs` and then download the Excel file titled `Genotypes.xlsx`. (Click on `Genotypes.xlsx` and then click `Download`.)
\
The first line of the data file shows you four things, each in a cell: 1) the number of loci, 2) the number of individuals, 3) the number of populations, and 4) the number of individuals in the first population. Enter this below:
\
\
*Number of loci:*___________________________________________________
\
\
*Number of individuals:*____________________________________________
\
\
*Number of populations:*____________________________________________
\
\
*Number of individuals in population #1:*___________________________
\
\
The third line of the file begins the genotype data. Column 1 has the individual ID, column 2 has the population name, and columns 3 and 4 have the two alleles for each individual (these individuals are diploid) at a particular locus. The alleles are coded as 1 or 2 (e.g., these might represent A and T at a single nucleotide polymorphism).
\
\
*What is the genotype of individual J19?*
\
\
\
\
*What is the allele frequency of allele #1?*
\
(Hint: Refer to the first page of the lab if you forget how to calculate allele frequencies. In Excel, simply click on a blank cell and type `=`. Then count the number of times allele 1 appears and type that after the `=`. Divide that by the total number of alleles in the population. Hit `enter`.)
\
\
\
\
*What is the allele frequency of allele #2?*
\
\
\
\
*What is your expected heterozygosity ($H_{e}$)?*
\
(Hint: Refer to the first section of the lab if you forget how to calculate $H_{e}$. In Excel, simply click on a blank cell and type `=2`. Then multiply that two by the two allele frequencies you just calculated. Hit `enter`.)
\
\
\
\
*What is your observed heterozygosity ($H_{o}$)?*
\
(Hint: Refer to the first section of the lab if you forget how to calculate $H_{o}$. In Excel, simply click on a blank cell and type `=`. Then count the number of heterozygotes in the population and type that after the `=`. Divide that by the total number of individuals in the population. Hit `enter`.)
\
\
\
\
*How does the expected heterozygosity compare to the maximum possible heterozygosity for a biallelic locus?*
\
\
\
\
*What are the implications of a very low heterozygosity for an individual locus? Why?*
\
\
\
\
\
\
*Do the observed and expected heterozygosities match? Using your judgment, does the population seem to be in Hardy-Weinberg equilibrium at this locus?*
\
*(Hint: $H_{e}$ is expected heterozygosity assuming population is at HWE.)*
\
\
\
\
\
\
Exit out of Excel when you are done.

## *__Understanding the inbreeding coefficient__*
\
We can also calculate a metric denoted as $F_{IS}$, otherwise known as the inbreeding coefficient. This can be thought of as the probability that two alleles at a given locus are identical by descent (inherited from same ancestor). It also represents the mean *reduction* in the *heterozygosity* of an individual due to inbreeding, or non-random mating within a subpopulation. Its value can range from -1 to 1, with 1 indicating a complete reduction in heterozygosity (all individuals are homozygous at a given locus).
\
\
We can estimate the inbreeding coefficient ($F_{IS}$) for an individual by hand using the following formula:
\
$F = 1 - [H_{o}/H_{e}]$
\
\
*What do you think an $F_{IS}$ of 0 indicates?*
\
\
\
\
*Using your previously calculated values of $H_{e}$ and $H_{o}$, what is the inbreeding coefficient for individual J19? (Show your work.)*
\
\
\
\
\
\
*How does inbreeding affect long-term population fitness? Why?*