---
title: "$F_{ST}$ From Transcriptomic  Data"
output: 
  html_notebook: default
  github_document: default
---

In this lab, we are going to investigate $F_{ST}$ values. $F_{ST}$ values (or fixation indices) are a measure of population differentiation due to population structure. They compare the amount of variation among subpopulations to the amount of variation in the entire population.
\
\
$F_{ST}$ values range from 0 to 1. A value of 0 indicates that there is no differentiation among subpopulations (all subpopulations have the same allele frequencies). A value of 1 indicates complete differentiation among subpopulations (all subpopulations are fixed for different alleles).
\
\
We have looked at $F_{ST}$ values before when we ran BayeScan and identified $F_{ST}$ outliers, or loci that diverge more than "expected" due to selection. Selection is not the only evolutionary process that can affect $F_{ST}$ values, however. Gene flow can also impact $F_{ST}$ values, as it tends to decrease the amount of differentiation between subpopulations.
\
\
*Would gene flow increase or decrease $F_{ST}$ values? Why?*
\
\
\
\
\
\
*Can you think of any other evolutionary processes that may impact $F_{ST}s$, besides selection and gene flow? Explain your answer.*
\
\
\
\
\
\
Go ahead and log in to Turing.

## *$F_{ST}s$ with vcftools*

\
We are going to calculate $F_{ST}$ values for our clownfish dataset using vcftools. This will give us an estimate of how much variation there is among our clownfish subpopulations (Japan, Indonesia, and the Philippines).
\
\
On Turing, navigate to your sandbox, and get a node to work on:
```{bash, eval=FALSE}
salloc -c 12
```
\
Open up the text file with the candidate loci that we identified yesterday by typing (all on one line)
```{bash, eval=FALSE}
less /cm/shared/courses/Bioinfo_Workshop/clownfish_data/outlier_candnames.txt
```
\
Do these loci look familiar? They should. This text file is a list of all the candidate loci for selection that we identified yesterday with BayeScan and BayPass. We are going to exclude these from our analysis today, as we already know they are $F_{ST}$ outliers (and thus will not accurately represent any population differentiation due to population structure).
\
\
To calculate $F_{ST}s$ between Japan and the Philippines using vcftools, type the following
```{bash, eval=FALSE}
enable_lmood
module load vcftools/0.1
```
\
Type (all on one line)
```{bash, eval=FALSE}
vcftools --vcf /cm/shared/courses/Bioinfo_Workshop/clownfish_data/output.hicov2.snps.only.vcf --exclude-positions /cm/shared/courses/Bioinfo_Workshop/clownfish_data/outlier_candnames.txt --weir-fst-pop J_individuals.txt --weir-fst-pop P_individuals.txt --out FST_J-P
```
\
Arguments we used:

* **--vcf** ------------------- read in data from a VCF file
* **--exclude-positions** ----- specify name of text file with loci to exclude from analysis
* **--weir-fst-pop** ---------- specify name of the text file with populations for analysis
* **--out** ------------------- specify name of the output file

Once vcftools has finished running, you will see some information printed to the screen.
\
\
*What is the Weir and Cockerham mean $F_{ST}$ estimate for Japan-Philippines?*
\
\
\
\
Open up the FST_J-P.weir.fst output file. Each line in the file corresponds to a SNP. This file has columns in the following order:

* Chromosome ID
* SNP bp position
* Weir and Cockerham $F_{ST}$ estimate (a commonly used estimator for $F_{ST}$

Search for chromosome TRINITY_DN39030_c1_g1_i1, SNP position 686.
\
\
*What is the $F_{ST}$ estimate for this SNP?*
\
\
\
\
*Is this SNP highly differentiated between the two populations, or not? How can you tell? (Hint: $F_{ST}s$ > 0.15 are generally considered to be highly differentiated.)*
\
\
\
\
\
\
*Is there a lot of genetic differentiation between these two populations? (Hint: look at the mean $F_{ST}$ estimate you recorded earlier.)*
\
\
\
\
Now repeat the $F_{ST}$ calculation for Japan-Indonesia (use --out FST_J-N) and Philippines-Indonesia (use --out FST_P-N). Make sure you are including the correct population files!
\
\
*What are the Weir and Cockerham mean $F_{ST}$ values for each pair of populations (there should be three pairs)?*
\
\
\
\
*Which population pair has the highest Weir and Cockerham mean $F_{ST}$?*
\
\
\
\
*Which population pair has the lowest Weir and Cockerham mean $F_{ST}$?*
\
\
\
\
*Do the $F_{ST}$ values appear to better fit an island model (all $F_{ST}s$ about equal) or an isolation-by-distance model ($F_{ST}s$ are lower for populations that are geographically closer)?*
\
\
\
\
Close out of any file you may have open.

## *__$F_{ST}$ and gene flow__*

We know that gene flow impacts $F_{ST}$ values. Thus, one might be tempted to use $F_{ST}s$ to estimate migration rates between populations. One way to do so uses the island model formula:

$F_{ST} = 1/(4Nm + 1)$

In this formula, *N* represents the population size and *m* represents the migration rate between populations (as a proportion). The island model assumes that all populations are of equal size and migration rates are the same for all populations as well. Often, these terms are combined together, as we are generally interested in the number of migrant individuals among populations (*Nm*).
\
\
Go ahead and use the island model formula to calculate the number of migrant individuals (*Nm*) for Japan-Philippines. Use the Weir and Cockerham mean $F_{ST}$ estimate you wrote down earlier.
\
\
*How many migrants per generation (Nm) does this calculation suggest these populations receive? Does this seem reasonable?*
\
\
\
\
\
\
*If we assume a population size of 100 clownfish, what would our migration rate be? (Hint: Solve for m in the equation with N = 10 and $F_{ST}$ = your Weir and Cockerham mean $F_{ST}$ estimate.)*
\
\
\
\
\
\
The island model makes many assumptions about our dataset and the demographic patterns at work. These assumptions are as follows:

1. Infinite number of populations
2. All populations are the same size
3. Each population exchanges migrants at the same rate
4. Populations are at HWE

*Think back to what you know about our clownfish dataset. To what extent do our data emet these assumptions?*
\
\
\
\
\
\
*Do you think the island model formula is a useful tool for estimating migration rates? Why or why not?* 